"""deputy.toml — declarative config, plus the built-in semantic-release defaults.

Every command reads its flags from three layers, most-specific first:

    CLI flag / env var   ->   deputy.toml   ->   built-in default

so a workflow can keep the static bits (marker, gitops target, release knobs) in
``deputy.toml`` and pass only what changes per run (``--tag``, ``--image``) on the
command line. deputy ships the full semantic-release default config itself, so a
repo needs no external ``action_config.toml`` — at most a few ``[release]``
overrides.
"""

from __future__ import annotations

import os
import tempfile
import tomllib
from pathlib import Path
from typing import Any

import tomli_w

DEFAULT_CONFIG_FILE = "deputy.toml"

# The semantic-release configuration deputy renders when a repo doesn't override
# it. Mirrors what a hand-written [tool.semantic_release] block used to provide,
# so `deputy tag-on-merge` works with zero release config. Every key here is
# overridable via deputy.toml's [release] table (deep-merged over this).
RELEASE_DEFAULTS: dict[str, Any] = {
    "version_toml": ["pyproject.toml:project.version"],
    "assets": [],
    "commit_message": "{version}\n\nAutomatically generated by python-semantic-release",
    "commit_parser": "angular",
    "logging_use_named_masks": False,
    "major_on_zero": True,
    "tag_format": "v{version}",
    "branches": {"main": {"match": "(main|master)", "prerelease_token": "rc", "prerelease": False}},
    "commit_parser_options": {
        "allowed_tags": ["chore", "feat", "fix"],
        "minor_tags": ["feat"],
        "patch_tags": ["fix", "perf"],
    },
    "remote": {
        "name": "origin",
        "type": "github",
        "ignore_token_for_push": True,
        "token": {"env": "GH_TOKEN"},
    },
    "publish": {"upload_to_vcs_release": True},
}


def deep_merge(base: dict, over: dict) -> dict:
    """Recursively merge ``over`` onto ``base`` (lists/scalars replace, not append)."""
    out = dict(base)
    for key, val in over.items():
        if isinstance(val, dict) and isinstance(out.get(key), dict):
            out[key] = deep_merge(out[key], val)
        else:
            out[key] = val
    return out


def load_config(path: str | None = None) -> dict:
    """Load deputy.toml. Order: explicit ``path`` arg, ``$DEPUTY_TOML``, then
    ``./deputy.toml``. Returns ``{}`` when no file is found — deputy runs fine on
    built-in defaults alone."""
    candidate = path or os.environ.get("DEPUTY_TOML") or DEFAULT_CONFIG_FILE
    p = Path(candidate)
    if not p.is_file():
        return {}
    with p.open("rb") as fh:
        return tomllib.load(fh)


def render_release_config(overrides: dict | None = None) -> str:
    """Return TOML text for a semantic-release config: defaults ⊕ ``overrides``."""
    merged = deep_merge(RELEASE_DEFAULTS, overrides or {})
    return tomli_w.dumps({"tool": {"semantic_release": merged}})


def write_release_config(overrides: dict | None = None) -> str:
    """Render the effective semantic-release config to a temp file; return its path.

    semantic-release is a subprocess that wants a config file (``-c``); this hands
    it one built from deputy's defaults and the repo's ``[release]`` overrides.
    """
    text = render_release_config(overrides)
    fd, name = tempfile.mkstemp(prefix="deputy-release-", suffix=".toml")
    with os.fdopen(fd, "w", encoding="utf-8") as fh:
        fh.write(text)
    return name


# ── gitops targets ────────────────────────────────────────────────────────────


def gitops_targets(cfg: dict) -> list[dict]:
    return list(cfg.get("gitops", []))


def find_target(cfg: dict, name: str) -> dict:
    for t in gitops_targets(cfg):
        if t.get("name") == name:
            return t
    raise KeyError(f"no [[gitops]] target named {name!r} in deputy.toml")


# ── release-watch targets ─────────────────────────────────────────────────────


def release_watch_targets(cfg: dict) -> list[dict]:
    return list(cfg.get("release_watch", []))


def find_release_watch_target(cfg: dict, name: str) -> dict:
    for t in release_watch_targets(cfg):
        if t.get("name") == name:
            return t
    raise KeyError(f"no [[release_watch]] target named {name!r} in deputy.toml")


def resolve_image_ref(cfg: dict, image: str) -> str:
    """Resolve a target's ``image`` field: a key in the ``[images]`` map, or a
    literal ref if it isn't mapped."""
    return cfg.get("images", {}).get(image, image)


def compose_image(ref: str, tag: str | None) -> str:
    """``ref`` + ``tag`` -> ``ref:tag``. If ``tag`` is falsy, ``ref`` is assumed to
    already carry a tag and is returned unchanged."""
    return f"{ref}:{tag}" if tag else ref


def fill_template(text: str, **values: str) -> str:
    """Substitute ``{name}`` placeholders without tripping on other braces."""
    for key, val in values.items():
        text = text.replace("{" + key + "}", val)
    return text
